version: "3"
services:
  springboot_vue:
    build: /vilce/application/springbootVue
    image: mydockerhub.com:5000/springboot_vue:${tag}
    container_name: springboot_vue
    ports:
      - "8006:8006"
    volumes:
      - /vilce/application/springbootVue/config:/vilce/application/springbootVue/config
      - /vilce/application/springbootVue/springboot_log:/vilce/application/springbootVue/springboot_log
      - /vilce/img:/vilce/img

  vuejs:
    build: /vilce/application/vuejs
    image: mydockerhub.com:5000/vuejs:${tag}
    container_name: vuejs
    ports:
      - "8007:80"

networks:
  default:
    external:
      name: my_net
