## 服务端口
server:
  port: 8010
# 配置以mysql为例，当然erupt也支持其他管理型数据库，如Oracle、PostgreSQL、SQL Server等
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/erupt?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: vilce
    password: lcz@190301
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
